//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppMVC1
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_Users
    {
        public int IdEmployee { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public Nullable<int> IdProfile { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string Login { get; set; }
    }
}
